package com.dtevgeny.blitzstat.database;

import android.arch.persistence.db.SupportSQLiteDatabase;
import android.arch.persistence.room.Database;
import android.arch.persistence.room.Room;
import android.arch.persistence.room.RoomDatabase;
import android.content.Context;
import android.support.annotation.NonNull;

import com.dtevgeny.blitzstat.database.dao.FriendDao;
import com.dtevgeny.blitzstat.database.dao.GameDao;
import com.dtevgeny.blitzstat.database.dao.GamePlayerDao;
import com.dtevgeny.blitzstat.database.dao.GamePlayerResultDao;
import com.dtevgeny.blitzstat.database.dao.GameWinnerDao;
import com.dtevgeny.blitzstat.database.dao.RoundDao;
import com.dtevgeny.blitzstat.database.dao.RoundScoreDao;
import com.dtevgeny.blitzstat.database.dao.RoundWinnerDao;
import com.dtevgeny.blitzstat.database.entity.Friend;
import com.dtevgeny.blitzstat.database.entity.Game;
import com.dtevgeny.blitzstat.database.entity.GamePlayer;
import com.dtevgeny.blitzstat.database.entity.GameWinner;
import com.dtevgeny.blitzstat.database.entity.Round;
import com.dtevgeny.blitzstat.database.entity.RoundScore;
import com.dtevgeny.blitzstat.database.entity.RoundWinner;

@Database( entities = { Friend.class, Game.class, GamePlayer.class, GameWinner.class, Round.class, RoundScore.class, RoundWinner.class }, version = 1 )
public abstract class AppDatabase extends RoomDatabase {

	public abstract GameDao gameDao();

	public abstract GamePlayerDao gamePlayerDao();

	public abstract GameWinnerDao gameWinnerDao();

	public abstract RoundDao roundDao();

	public abstract RoundScoreDao roundScoreDao();

	public abstract RoundWinnerDao roundWinnerDao();

	public abstract FriendDao friendDao();

	public abstract GamePlayerResultDao gamePlayerResultDao();

	private static AppDatabase INSTANCE;

	private static final RoomDatabase.Callback RDC = new RoomDatabase.Callback() {
		@Override
		public void onCreate( @NonNull SupportSQLiteDatabase db ) {

			db.execSQL( "insert into friends (player_id, firstName, lastName, nick) values\n" +
					"\t(1, 'Евгений', 'ДТ', null),\n" +
					"\t(2, 'Анна', 'Филина', 'Neko'),\n" +
					"\t(3, 'Ирина', 'Озябкина', 'Айрин'),\n" +
					"\t(4, 'Татьяна', 'Коробец', 'Элли'),\n" +
					"\t(5, 'Ева', 'Белич', null),\n" +
					"\t(6, 'Станислав', 'Бредихин', 'Мар'),\n" +
					"\t(7, 'Диана', '', null),\n" +
					"\t(8, 'Елена', '', null),\n" +
					"\t(9, 'Светлана', '', null)\n" +
					";" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 5 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -7 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 18 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 1 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 16 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 18 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -4 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, -11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 18 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, -11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 5, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 7 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 5 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 21 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 21 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 7 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 27 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -4 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -1 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -1 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 1 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 8 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 19 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 0 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 19 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -1 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -15 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 7 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 25 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 10 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 7 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 5 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 21 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 15 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -4 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 18 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 7 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 16 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -4 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -6 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 20 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 20 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 21 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 21 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 16 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 16 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 22 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 21 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 19 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 1 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 9 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 7 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 19 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, -4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 6 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 16 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 19 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, -7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 18 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, -9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -1 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 26 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -5 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, -10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, -10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, -17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 16 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 26 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 20 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 20 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 22 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 9 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 7 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 18 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 16 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 18 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 17 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, -5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 23 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, -8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, -7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -15 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 17 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, -5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 9, 21 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 7, 18 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 7 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 11 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 17 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 14 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -6 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 18 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 16 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 12 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 10 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 3 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 1 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );

			db.execSQL( "INSERT INTO games ( dtStart ) VALUES ( CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 4 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 3 );" );
			db.execSQL( "INSERT INTO gamePlayers ( game_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 20 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 18 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 19 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -2 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 9 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -5 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -8 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 11 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 16 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 26 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 15 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 1 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 0 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, -12 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, -10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 8 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 6 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 1 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 13 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 0 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 7 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 10 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 17 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, -6 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 22 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 13 );" );
			db.execSQL( "INSERT INTO rounds ( game_id, dtEnd ) VALUES ( ( SELECT MAX( id ) FROM games ), CURRENT_TIMESTAMP );" );
			db.execSQL( "INSERT INTO roundWinners ( round_id, friend_id ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 4, 7 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 3, 15 );" );
			db.execSQL( "INSERT INTO roundScores ( round_id, friend_id, score ) VALUES ( ( SELECT MAX( id ) FROM rounds ), 2, 14 );" );
			db.execSQL( "INSERT INTO gameWinners (game_id, friend_id) VALUES ( ( SELECT MAX( id ) FROM games ), 2 );" );


			super.onCreate( db );
		}

		@Override
		public void onOpen( @NonNull SupportSQLiteDatabase db ) {
			super.onOpen( db );
		}
	};

	public static AppDatabase getInstance( Context context ) {
		if ( INSTANCE == null ) {


			INSTANCE = Room.databaseBuilder(
					context.getApplicationContext(),
					AppDatabase.class,
					"blitzStatDatabase"
			).addCallback( RDC ).allowMainThreadQueries().build();    // TODO delete allowMainThreadQueries()
		}

		return INSTANCE;
	}

	public void destroyInstance() {
		INSTANCE = null;
	}


}
